### ISSUE TITLE
Document the copyright holder(s) in LICENSE file

### ISSUE THREAD

**Issue by medicalwei** [adobe-type-tools/cffsubr#16]
I apologize for my non-font-related issue.

I am going to package this into Debian as a dependency of fontmake, however I found no concrete copyright holder info inside this repo: This repo is in `adobe-type-tools` team but the author in `setup.py` is @anthrotype.

Could you indicate to me that who the copyright holder is for me to continue packaging? Thank you!

**Comment by anthrotype** [comment]
I propose we use the same author and copyright holder as the other Adobe type tools. Can you send a PR? Thanks
