### ISSUE TITLE
tx 1.2.3 bug with three-byte integers

### ISSUE THREAD

**Issue by dscorbett** [adobe-type-tools/cffsubr#22]
cffsubr uses tx 1.2.3, which has a bug: it seems to interpret three-byte integers as unsigned, whereas they should be signed. I noticed this with fontTools 4.41.0, which since fonttools/fonttools#3200 can produce three-byte integers.

To reproduce the problem, I created [a minimal OTF](https://github.com/adobe-type-tools/cffsubr/files/12032373/test.otf.zip) based on the instructions in [fontBuilder.py](https://github.com/fonttools/fonttools/blob/4.41.0/Lib/fontTools/fontBuilder.py#L75), except that before saving I ran `fb.font['CFF '].cff[0].UnderlinePosition = -1315`. cffsubr changes the underline position to 64221.

```console
$ cffsubr -o test.subr.otf test.otf
$ ttx -q -t CFF test.subr.otf | grep UnderlinePosition 
      <UnderlinePosition value="64221"/>
```

tx 1.3.0 works. It would probably be best to upgrade to the latest version.

```console
$ /opt/homebrew/bin/tx -v | grep tx
    tx        1.3.0
$ cp /opt/homebrew/bin/tx venv/lib/python3.11/site-packages/cffsubr/tx
$ cffsubr -o test.subr1.otf test.otf
$ ttx -q -t CFF test.subr1.otf | grep UnderlinePosition
      <UnderlinePosition value="-1315"/>
```

**Comment by josh-hadley** [comment]
@anthrotype do you want to take this on?

**Comment by dscorbett** [comment]
I updated the submodule, built it, and installed it, but building cffsubr’s wheel failed:
```
  × Building wheel for cffsubr (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      running bdist_wheel
      running build
      running build_py
      copying src/cffsubr/_version.py -> build/lib.macosx-13-arm64-cpython-311/cffsubr
      running build_ext
      error: [Errno 2] No such file or directory: 'external/afdko/c/tx/build/osx/xcode'
      [end of output]
```

It does work if I don’t update the submodule, so maybe there was a change to AFDKO’s build system between versions 3.6.1 and 3.9.6.
